<?php

namespace App\Http\Controllers\Api\V1;

use App\Enums\IncentiveType;
use App\Enums\UserRole;
use App\Http\Controllers\Controller;
use App\Models\Study;
use App\Services\StudyFeedService;
use App\Services\StudyMatchingService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

/**
 * API — Study Recommendation Feed  (Member 4, graded feature)
 *
 * No ranking logic here. Guard, validate the filters, call
 * StudyFeedService, shape JSON.
 *
 * THE PAYLOAD RECONCILES
 * ----------------------
 * Each study's three feed_breakdown contributions add up to its feed_score,
 * and the weights are returned alongside so the arithmetic can be checked on
 * screen. Same discipline as the matching and reliability payloads.
 *
 * NOTE: this endpoint NEVER makes an outbound HTTP call. The AI advice lives
 * behind /participants/me/skill-gap and is only ever generated by an explicit
 * POST or the artisan command — see SkillGapApiController.
 */
class FeedApiController extends Controller
{
    public function __construct(
        private StudyFeedService $feed,
        private StudyMatchingService $matching,
    ) {}

    /**
     * GET /api/v1/participants/me/feed
     *
     * Query: incentive_type, method, max_duration, topic_ids[], strong_only, limit
     */
    public function index(Request $request): JsonResponse
    {
        $user = $this->participantOrFail($request);

        $filters = $request->validate([
            'incentive_type' => ['sometimes', Rule::in(array_column(IncentiveType::cases(), 'value'))],
            'method'         => ['sometimes', Rule::in(['online', 'in_person'])],
            'max_duration'   => ['sometimes', 'integer', 'between:1,600'],
            'topic_ids'      => ['sometimes', 'array', 'max:10'],
            'topic_ids.*'    => ['integer', 'exists:topics,id'],
            'strong_only'    => ['sometimes', 'boolean'],
            'limit'          => ['sometimes', 'integer', 'between:1,50'],
        ]);

        // Unknown filter values are rejected above rather than ignored, so a
        // typo cannot quietly return the whole feed.

        $limit = (int) ($filters['limit'] ?? $this->feed->pageSize());

        $applied = collect($filters)->except('limit')->all();

        if (isset($applied['topic_ids'])) {
            $applied['topic_ids'] = array_map('intval', $applied['topic_ids']);
        }

        $studies = $this->feed->feed($user, $applied, $limit);

        return response()->json([
            'data' => [
                'user_id'          => $user->id,
                'count'            => $studies->count(),
                'filters_applied'  => (object) $applied,
                'weights'          => $this->feed->weights(),
                'strong_threshold' => $this->matching->strongThreshold(),
                'studies'          => $studies->map(fn (Study $s) => $this->payload($s))->all(),
            ],
        ], 200);
    }

    /**
     * GET /api/v1/participants/me/feed/filters
     *
     * The options the page should offer. Returned by the API rather than
     * hardcoded in JavaScript, so adding a topic or an incentive type updates
     * the interface with no frontend change.
     */
    public function filters(Request $request): JsonResponse
    {
        $this->participantOrFail($request);

        return response()->json(['data' => $this->feed->filterOptions()], 200);
    }

    // -----------------------------------------------------------------

    private function payload(Study $study): array
    {
        return [
            'study_id'            => $study->id,
            'title'               => $study->title,
            'description'         => $study->description,
            'category'            => $study->category,
            'method'              => $study->method,
            'duration_minutes'    => $study->duration_minutes,
            'incentive_type'      => $study->incentive_type?->value,
            'compensation_amount' => $study->compensation_amount,
            'slots'               => (int) $study->slots,
            'deadline'            => $study->deadline?->format('d M Y'),
            'researcher_name'     => $study->researcher?->name,
            'topics'              => $study->getAttribute('topics') ?? [],

            // Suitability — straight from the matching engine, not recomputed.
            'match_score'      => $study->match_score,
            'strong_match'     => (bool) $study->strong_match,
            'match_reasons'    => $study->match_reasons ?? [],
            'criteria_summary' => $study->criteria_summary,

            // Feed position. The three contributions sum to feed_score.
            'feed_score'     => $study->feed_score,
            'feed_breakdown' => $study->feed_breakdown,

            'url' => route('studies.show', $study),
        ];
    }

    private function participantOrFail(Request $request)
    {
        $user = $request->user();

        abort_unless(
            $user->role === UserRole::PARTICIPANT,
            403,
            'Only participants have a study feed.'
        );

        abort_if(
            ! $user->participantProfile,
            404,
            'No participant profile found for this account.'
        );

        return $user;
    }
}
