<?php

namespace App\Http\Controllers;

use App\Models\PushSubscription;
use App\Models\UserNotification;
use App\Services\NotificationService;
use App\Services\WebPushService;
use Illuminate\Http\Request;

/**
 * FEATURE 4 — Notification centre + Web Push (external API).
 */
class NotificationController extends Controller
{
    public function __construct(
        private NotificationService $notifications,
        private WebPushService $push,
    ) {}

    public function index()
    {
        $user = auth()->user();

        $prefs = $user->notificationPreference
            ?? $user->notificationPreference()->create([]);

        $items = UserNotification::where('user_id', $user->id)
            ->latest('id')
            ->take(20)
            ->get();

        return view('notifications.index', [
            'user'          => $user,
            'prefs'         => $prefs,
            'types'         => NotificationService::TYPES,
            'items'         => $items,
            'unread'        => $this->notifications->unreadCount($user),
            'pushReady'     => $this->push->isConfigured(),
            'vapidKey'      => $this->push->publicKey(),
            'subscriptions' => PushSubscription::where('user_id', $user->id)->get(),
        ]);
    }

    /** Save the five on/off switches. */
    public function updatePreferences(Request $request)
    {
        $prefs = auth()->user()->notificationPreference;

        $update = [];

        foreach (NotificationService::TYPES as $key => $type) {
            // An unchecked checkbox sends nothing at all, so absence = off.
            $update[$type['column']] = $request->boolean($key);
        }

        $prefs->update($update);

        return back()->with('status', 'Notification preferences saved.');
    }

    /**
     * The browser calls this after the user grants permission.
     * The endpoint and keys are generated by the browser's push service —
     * we only store them.
     */
    public function subscribe(Request $request)
    {
        $data = $request->validate([
            'endpoint'         => ['required', 'string'],
            'keys.p256dh'      => ['required', 'string'],
            'keys.auth'        => ['required', 'string'],
            'contentEncoding'  => ['nullable', 'string'],
        ]);

        PushSubscription::updateOrCreate(
            [
                'user_id'       => auth()->id(),
                'endpoint_hash' => PushSubscription::hashFor($data['endpoint']),
            ],
            [
                'endpoint'         => $data['endpoint'],
                'public_key'       => $data['keys']['p256dh'],
                'auth_token'       => $data['keys']['auth'],
                'content_encoding' => $data['contentEncoding'] ?? 'aesgcm',
                'last_used_at'     => now(),
            ]
        );

        return response()->json(['ok' => true]);
    }

    /** The browser calls this if the user revokes permission. */
    public function unsubscribe(Request $request)
    {
        $data = $request->validate(['endpoint' => ['required', 'string']]);

        PushSubscription::where('user_id', auth()->id())
            ->where('endpoint_hash', PushSubscription::hashFor($data['endpoint']))
            ->delete();

        return response()->json(['ok' => true]);
    }

    /** Send yourself one, to prove the whole chain works. */
    public function test()
    {
        $notification = $this->notifications->send(
            auth()->user(),
            'studies',
            'Test notification from TRYBE',
            'If you can see this in your browser, push is working end to end.',
            url('/notifications')
        );

        if (! $notification) {
            return back()->with('status',
                'That type is switched off, so nothing was sent. Turn on "New studies" and try again.');
        }

        return back()->with('status', 'Test sent — ' . $notification->push_result . '.');
    }

    public function markAllRead()
    {
        UserNotification::where('user_id', auth()->id())
            ->unread()
            ->update(['read_at' => now()]);

        return back()->with('status', 'All notifications marked as read.');
    }
}
